import { cookies } from "next/headers";
import { getIronSession, type SessionOptions } from "iron-session";
import type { CaptchaQuestion } from "@/app/verify/actions";
// Static JSON import — webpack inlines the file at build time so the
// content ships with the function regardless of tracing behaviour.
// Generated by scripts/fetch-captcha-images.ts. Relative path (no `@/`
// alias) because runtime resolution of aliases can't fall back on
// webpack's rewrite.
import manifest from "../../../../lib/captcha/_images.generated.json";

type CaptchaSession = {
  questions?: CaptchaQuestion[];
  current?: number;
  streak?: number;
};

function captchaSessionOptions(): SessionOptions {
  const password = process.env.SESSION_SECRET;
  if (!password || password.length < 32) throw new Error("SESSION_SECRET missing");
  return {
    cookieName: "smse_captcha",
    password,
    cookieOptions: {
      secure: process.env.NODE_ENV === "production",
      httpOnly: true,
      sameSite: "lax" as const,
      path: "/",
      maxAge: 60 * 30,
    },
  };
}

const CAPTCHA_IMAGES = manifest as Record<string, string>;

export async function GET() {
  const cookieStore = await cookies();
  const session = await getIronSession<CaptchaSession>(cookieStore, captchaSessionOptions());

  const { questions, current = 0 } = session;
  if (!questions?.length) {
    return new Response("No active challenge", { status: 404 });
  }

  const imageName = questions[current].image;
  // Defence in depth: only accept `\d+\.jpg` — keeps a compromised session
  // from escaping the manifest via weird keys.
  if (!/^\d+\.jpg$/.test(imageName)) {
    return new Response("Invalid image", { status: 400 });
  }

  const base64 = CAPTCHA_IMAGES[imageName];
  if (!base64) {
    return new Response("Image not found", { status: 404 });
  }
  const buffer = Buffer.from(base64, "base64");
  return new Response(buffer, {
    headers: {
      "Content-Type": "image/jpeg",
      "Cache-Control": "no-store",
    },
  });
}
